In [1]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [7]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

## Working with dates

In [9]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

## 1. Extract year

In [13]:
date['date_year']=date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## 2. Extract month

In [14]:
date['date_month_name']=date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_name
0 2019-12-10        5628       25       3       2019               12
1 2018-08-15        3646       14     157       2018                8
2 2018-10-23        1859       25       1       2018               10
3 2019-08-17        7292       25       1       2019                8
4 2019-01-06        4344       25       3       2019                1

In [15]:
date['date_month_name']=date['date'].dt.month_name()

date.head()

        date  product_id  city_id  orders  date_year date_month_name
0 2019-12-10        5628       25       3       2019        December
1 2018-08-15        3646       14     157       2018          August
2 2018-10-23        1859       25       1       2018         October
3 2019-08-17        7292       25       1       2019          August
4 2019-01-06        4344       25       3       2019         January

## Extract days

In [16]:
date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year date_month_name  date_day
0 2019-12-10        5628       25       3       2019        December        10
1 2018-08-15        3646       14     157       2018          August        15
2 2018-10-23        1859       25       1       2018         October        23
3 2019-08-17        7292       25       1       2019          August        17
4 2019-01-06        4344       25       3       2019         January         6

In [17]:
# day of the week
date['date_dow']=date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

In [20]:
# day of the week - name
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id', 'city_id', 'orders']).head()

        date  date_year date_month_name  date_day  date_dow date_dow_name
0 2019-12-10       2019        December        10         1       Tuesday
1 2018-08-15       2018          August        15         2     Wednesday
2 2018-10-23       2018         October        23         1       Tuesday
3 2019-08-17       2019          August        17         5      Saturday
4 2019-01-06       2019         January         6         6        Sunday

In [21]:
# is weekend?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

## Extract week of the year

In [22]:
# Extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,0,50
1,2018-08-15,2018,August,15,2,Wednesday,0,33
2,2018-10-23,2018,October,23,1,Tuesday,0,43
3,2019-08-17,2019,August,17,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

## Extract Quarter

In [23]:
# Extract Quarter
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,January,6,6,Sunday,1,1,1

## Extract semester

In [24]:
# Extract Semester
date['semester'] = np.where(date['date'].dt.month <= 6, 1, 2)

date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,1

## Extract time elapsed beteen dates

In [25]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 10, 14, 0, 22, 6, 58675)

In [26]:
today - date['date']

0     2500 days 00:22:06.058675
1     2982 days 00:22:06.058675
2     2913 days 00:22:06.058675
3     2615 days 00:22:06.058675
4     2838 days 00:22:06.058675
                 ...
995   2928 days 00:22:06.058675
996   2869 days 00:22:06.058675
997   2717 days 00:22:06.058675
998   2782 days 00:22:06.058675
999   2556 days 00:22:06.058675
Name: date, Length: 1000, dtype: timedelta64[us]

In [27]:
(today - date['date']).dt.days

0      2500
1      2982
2      2913
3      2615
4      2838
       ...
995    2928
996    2869
997    2717
998    2782
999    2556
Name: date, Length: 1000, dtype: int64

In [28]:
# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'M'),0)

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

In [29]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [30]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [31]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [32]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## Extract time part

In [33]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## Time difference

In [34]:
today - time['date']

0     4685 days 23:32:06.058675
1     4550 days 00:42:06.058675
2     5036 days 00:01:06.058675
3     4337 days 23:51:06.058675
4     4735 days 01:11:06.058675
                 ...
995   5324 days 23:32:06.058675
996   4646 days 01:08:06.058675
997   5111 days 00:45:06.058675
998   5227 days 00:48:06.058675
999   4499 days 00:57:06.058675
Name: date, Length: 1000, dtype: timedelta64[us]

In [35]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      4.048687e+08
1      3.931225e+08
2      4.351105e+08
3      3.748027e+08
4      4.091083e+08
           ...
995    4.600783e+08
996    4.014185e+08
997    4.415931e+08
998    4.516157e+08
999    3.887170e+08
Name: date, Length: 1000, dtype: float64

In [36]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.747812e+06
1      6.552042e+06
2      7.251841e+06
3      6.246711e+06
4      6.818471e+06
           ...
995    7.667972e+06
996    6.690308e+06
997    7.359885e+06
998    7.526928e+06
999    6.478617e+06
Name: date, Length: 1000, dtype: float64

In [37]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      112463.535016
1      109200.701683
2      120864.018350
3      104111.851683
4      113641.185016
           ...
995    127799.535016
996    111505.135016
997    122664.751683
998    125448.801683
999    107976.951683
Name: date, Length: 1000, dtype: float64